const db=supabase.createClient(OTG.url,OTG.key),momentsEl=document.getElementById('moments'),photoList=document.getElementById('photoList');let photoFiles=[],editingSlug=new URLSearchParams(location.search).get('edit');
const random=(n=16)=>Array.from(crypto.getRandomValues(new Uint8Array(n)),b=>(b%36).toString(36)).join('');
function addMoment(v={}){const row=document.createElement('div');row.className='moment-row';row.draggable=true;row.innerHTML=`<label>التاريخ<input class="m-date" value="${v.date||''}" placeholder="14.02.2024"></label><label>عنوان المرحلة<input class="m-title" value="${v.title||''}" placeholder="أول لقاء"></label><button type="button" class="remove">×</button><textarea class="m-text" rows="2" placeholder="ماذا حدث في هذه اللحظة؟">${v.text||''}</textarea>`;row.querySelector('.remove').onclick=()=>row.remove();row.addEventListener('dragstart',()=>row.classList.add('dragging'));row.addEventListener('dragend',()=>row.classList.remove('dragging'));momentsEl.appendChild(row)}
[{date:'14.02.2024',title:'أول لقاء',text:''},{date:'03.06.2024',title:'أول مغامرة',text:''},{date:'اليوم',title:'وما زالت الحكاية مستمرة',text:''}].forEach(addMoment);addMoment.onclick=null;document.getElementById('addMoment').onclick=()=>addMoment();
momentsEl.addEventListener('dragover',e=>{e.preventDefault();const y=e.clientY;const rows=[...momentsEl.querySelectorAll('.moment-row:not(.dragging)')];const next=rows.find(r=>y<r.getBoundingClientRect().top+r.offsetHeight/2);const dragging=momentsEl.querySelector('.dragging');if(dragging)momentsEl.insertBefore(dragging,next||null)});
document.getElementById('photos').onchange=e=>{photoFiles.push(...[...e.target.files].slice(0,15-photoFiles.length));renderPhotos();e.target.value=''};
function renderPhotos(){photoList.innerHTML='';photoFiles.forEach((item,i)=>{const file=item.file||item,src=item.src||URL.createObjectURL(file);const el=document.createElement('div');el.className='photo-item';el.draggable=true;el.innerHTML=`<img src="${src}"><button type="button">×</button><input placeholder="تعليق على الصورة" value="${item.caption||''}"><select><option value="center">توسيط الصورة</option><option value="top">إظهار الأعلى</option><option value="bottom">إظهار الأسفل</option></select>`;el.querySelector('select').value=item.position||'center';el.querySelector('img').style.objectPosition=item.position||'center';el.querySelector('button').onclick=()=>{photoFiles.splice(i,1);renderPhotos()};el.querySelector('input').oninput=e=>{photoFiles[i]=item.src?{...item,caption:e.target.value,position:el.querySelector('select').value}:{file,caption:e.target.value,position:el.querySelector('select').value}};el.querySelector('select').onchange=e=>{photoFiles[i]=item.src?{...item,caption:el.querySelector('input').value,position:e.target.value}:{file,caption:el.querySelector('input').value,position:e.target.value};el.querySelector('img').style.objectPosition=e.target.value};el.addEventListener('dragstart',()=>{el.dataset.drag='1'});el.addEventListener('dragover',e=>{e.preventDefault();const from=photoList.querySelector('[data-drag="1"]');if(from&&from!==el){const a=[...photoList.children].indexOf(from),b=[...photoList.children].indexOf(el);const moved=photoFiles.splice(a,1)[0];photoFiles.splice(b,0,moved);renderPhotos()}});photoList.appendChild(el)})}
for(const id of ['song','voice'])document.getElementById(id).onchange=e=>document.getElementById(id+'Name').textContent=e.target.files[0]?.name||'';
function collect(){return{language:language.value,names:`${name1.value} & ${name2.value}`,name1:name1.value,name2:name2.value,since:since.value,letter:letter.value,moments:[...momentsEl.children].map(r=>({date:r.querySelector('.m-date').value,title:r.querySelector('.m-title').value,text:r.querySelector('.m-text').value})).filter(x=>x.title),songTitle:songTitle.value,songSubtitle:'الأغنية التي تحمل صوت حكايتنا',unlock:unlock.value||null,futureMessage:futureMessage.value,photos:[]}}
async function upload(file,path){const {error}=await db.storage.from('memory-media').upload(path,file,{cacheControl:'31536000',upsert:false});if(error)throw error;return db.storage.from('memory-media').getPublicUrl(path).data.publicUrl}
async function save(preview=false){
 if(!memoryForm.reportValidity())return;
 const slug=editingSlug||random(14),token=editingSlug?localStorage.getItem(`otg-edit-${slug}`):random(36),content=collect();
 const fresh=photoFiles.filter(x=>!x.src),total=fresh.length+(song.files[0]?1:0)+(voice.files[0]?1:0),progress=document.getElementById('progress');let uploaded=0;publish.disabled=true;
 try{
  for(let i=0;i<photoFiles.length;i++){const item=photoFiles[i];if(item.src){content.photos.push(item);continue}const file=item.file||item,ext=(file.name.split('.').pop()||'jpg').toLowerCase();progress.textContent=`رفع الملفات ${++uploaded} من ${total}…`;content.photos.push({src:await upload(file,`${slug}/photo-${i}-${random(5)}.${ext}`),caption:item.caption||`ذكرى ${i+1}`,position:item.position||'center'})}
  if(song.files[0]){const f=song.files[0];progress.textContent=`رفع الملفات ${++uploaded} من ${total}…`;content.audio=await upload(f,`${slug}/song-${random(5)}.${f.name.split('.').pop()}`)}else if(window.oldContent?.audio)content.audio=window.oldContent.audio;
  if(voice.files[0]){const f=voice.files[0];progress.textContent=`رفع الملفات ${++uploaded} من ${total}…`;content.voice=await upload(f,`${slug}/voice-${random(5)}.${f.name.split('.').pop()}`)}else if(window.oldContent?.voice)content.voice=window.oldContent.voice;
  progress.textContent=editingSlug?'حفظ التعديلات…':'إنشاء الرابط الخاص…';const call=editingSlug?await db.rpc('update_memory',{p_slug:slug,p_token:token,p_content:content}):await db.rpc('create_memory',{p_slug:slug,p_token:token,p_content:content});if(call.error)throw call.error;if(!editingSlug)localStorage.setItem(`otg-edit-${slug}`,token);
  const url=`${location.origin}/m/${slug}`;if(preview){window.open(url,'_blank')}else{resultUrl.value=url;openUrl.href=url;editUrl.href=`/create?edit=${slug}`;done.showModal()}progress.textContent='تم بنجاح ✓';editingSlug=slug;
 }catch(e){progress.textContent='حدث خطأ: '+e.message}finally{publish.disabled=false}
}

async function loadEdit(){if(!editingSlug)return;const token=localStorage.getItem(`otg-edit-${editingSlug}`);if(!token){document.getElementById('progress').textContent='رابط التعديل متاح فقط من الجهاز الذي أنشأ الصفحة.';publish.disabled=true;return}const {data:r}=await db.rpc('get_memory',{p_slug:editingSlug});if(!r)return;const c=r.content;window.oldContent=c;language.value=c.language||'ar';const names=(c.names||' & ').split(' & ');name1.value=c.name1||names[0]||'';name2.value=c.name2||names[1]||'';since.value=c.since||'';letter.value=c.letter||'';songTitle.value=c.songTitle||'';unlock.value=c.unlock?.slice(0,16)||'';futureMessage.value=c.futureMessage||'';momentsEl.innerHTML='';(c.moments||[]).forEach(addMoment);photoFiles=c.photos||[];renderPhotos();publish.textContent='حفظ التعديلات ♡'}loadEdit();
memoryForm.onsubmit=e=>{e.preventDefault();save(false)};document.getElementById('preview').onclick=()=>save(true);document.getElementById('copyUrl').onclick=async()=>{await navigator.clipboard.writeText(resultUrl.value);copyUrl.textContent='تم النسخ ✓'};
